### ISSUE TITLE
Documantation is not deployed on push

### ISSUE THREAD

**Issue by matteobaratto** [teob97/grasp2alm#5]
Documentation is now deployed only when pushed from `docs` branch.
The correct behavior is to deploy documentation at every push on master branch. 

The problem is in the following file: `.github/workflows/gh-pages.yml`

```
name: Deploy Sphinx Document to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - docs
```
